### ISSUE TITLE
depense Familia _ Moh'd Bilani

### ISSUE THREAD

**Issue by bilani** [ISSAE/smb214-2015#3]
Project: Depense Familial
BY: Mohamad Bilani
URL: https://github.com/bilani/gestionDep.git

so far created is the java web application, using glassfish 4, connection pool and CRUD.

remaining tasks: REALm and the business reports.

**Comment by pascalfares** [comment]
Reported.

**Comment by bilani** [comment]
project is done with CRUD FileRealm and report

**Comment by pascalfares** [comment]
Added as submodule
