### ISSUE TITLE
Project Expenses Noel Achkar

### ISSUE THREAD

**Issue by nachkar** [ISSAE/smb214-2015#8]
Working now on j security check and jasper report

https://github.com/nachkar/Expenses

**Comment by nachkar** [comment]
Pushed a new version with j security check
Now working on jasper report

**Comment by nachkar** [comment]
Pushed a new version with jasper report.
Project Finished !!!!

**Comment by nachkar** [comment]
Mr Pascal @pascalfares I added the presentation for my project (PDF + Explication) at https://github.com/nachkar/Expenses/tree/master/Presentation%20SMB214
Thank you.

**Comment by pascalfares** [comment]
1- La presentation doit décrire une technologie relié a j2ee ou andoid
2- Un tutoriel.

Il faut venir faire une présentation

_____
_Il est toujours préférable de trouver une solution que de produire des
excuses_
_Pascal Fares http://www.cofares.net_

Enseignant ISAE - Cnam Liban
Chef du département informatique http://depinfo.isae.edu.lb Cnam Liban

2015-10-05 23:55 GMT+03:00 Noel Achkar notifications@github.com:
